# What is Slicing on List in Python
a=["John","Rock","Kane","Willson","Jacky"]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[-1])
print(a[-2])
print(a[-3])
print(a[-4])
print(a[-5])
print(a[1:4])
print(a[::])
print(a[:3])
print(a[2:])
